### ISSUE TITLE
Swiping Problem: PagingMenuController jumps back to previous ViewController

### ISSUE THREAD

**Issue by patricks** [kitasuke/PagingMenuController#111] opened 2015-10-20 21:13 UTC
Hi,

I have problem with your PagingMenuController. If I swipe from one view to another one, the ViewController jumps back to the previous one, while I swipe.

I have recorded a Screenrecording, of my problem, to get a better description.

You can watch it unter this link: https://dl.dropboxusercontent.com/u/215017/iphone_problem.mov

I hope this helps.

**Comment by kitasuke** [comment] 2015-10-21 02:13
There are two things I want to explain.
First one is that the screenrecording from 0 to 4 seconds. This looks like a bug. It should'n be back to first view which is "current " tab.

Second one is that the rest of screenrecording which is probably what you mentioned about is an expected behaviour with PagingMenuController.
The reason why it's menu tab jumps to another one is you swipe from initial position to half of the screen. It's just showing you are about to move to another paging view. 
Therefore, delegate method `willMoveToMenuPage ` won't be called untill you finish jumping to either of views.
This could be an option in the future, but this is what PagingMenuController does for now.

**Comment by patricks** [comment] 2015-10-21 06:36
Thanks for your infos, so how can I help you to fix this bug?

Should I build a striped down version of this app, so you can investigate further?

Or should I try to fix this on my own?

**Comment by kitasuke** [comment] 2015-10-21 06:43
Well, I already figured out what was wrong with. So I'm fixing this as soon as possible!

**Comment by patricks** [comment] 2015-10-21 06:44
Nice thanks! 👍

**Comment by kitasuke** [comment] 2015-10-21 06:45
I'll let you know once it's fixed.

**Comment by patricks** [comment] 2015-10-21 09:03
Hi, I figured out, if the font and selectedFont is from the same size and type it works much better 😄 

```swift
options.font = UIFont.systemFontOfSize(12)
options.selectedFont = UIFont.systemFontOfSize(12)
//options.selectedFont = UIFont.boldSystemFontOfSize(12)
```

**Comment by kitasuke** [comment] 2015-10-21 09:08
Yes, I knew `selectedFont` doesn't work properly any more #112 , but couldn't say whether it's related or not...
Anyway, I'll look into and fix it.
Thanks for your info!

**Comment by AndreJan** [comment] 2015-10-23 08:49
I had the same issue!
If you don't need different fonts/sizes in the current menu item

```
private func focusMenuItem() {
        // make selected item focused
        //menuItemViews.forEach { $0.focusLabel(menuItemViews.indexOf($0) == currentPage) }

        // make selected item foreground
        sortedMenuItemViews.forEach { $0.layer.zPosition = menuItemViews.indexOf($0) == currentPage ? 0 : -1 }
        
        setNeedsLayout()
        layoutIfNeeded()
    }
```
comment "menuItemViews.forEach" out.
You can find it in the MenuView.swift.

**Comment by kitasuke** [comment] 2015-10-24 10:24
It's fixed on master branch!
I'll let you know again once it's available with new version on CocoaPods or Carthage.

**Comment by kitasuke** [comment] 2015-10-24 14:47
Please use the latest version!

**Closed by kitasuke** 2015-10-24 14:47 UTC
Labels: bug
