### ISSUE TITLE
Custom Class

### ISSUE THREAD

**Issue by ds1239** [kitasuke/PagingMenuController#50] opened 2015-07-28 04:42 UTC
Hello,
I am trying to present a custom view controller in the pager controller, but I keep getting the following error printed:
2015-07-28 00:37:36.056 YidKit[529:59574] Attempt to add this NSLayoutConstraint to an engine in which it already exists.  This can cause engine corruption. Break on void _NSLayoutConstraintRedundantAdd() to debug.  This will be logged only once.  This may break in the future.
2015-07-28 00:37:36.061 YidKit[529:59574] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [nan 0; 375 50]'
*** First throw call stack:
(0x1839844d0 0x198303f9c 0x183984418 0x188808668 0x188808508 0x18903df44 0x18904c11c 0x18900d19c 0x100176a34 0x1001308b4 0x1890261c8 0x189025f50 0x100172bd0 0x10016e400 0x100167dcc 0x100167e00 0x188feb0ac 0x1888125b4 0x18880d1c0 0x1890014e4 0x10016d61c 0x1001681c0 0x100192668 0x1001926c8 0x188fef504 0x189007458 0x18919ae70 0x1890aaf4c 0x1890aac28 0x1890aab90 0x188feb070 0x1888125b4 0x18880d1c0 0x18880d080 0x18880c71c 0x18880c470 0x188fe13ac 0x18393b3f8 0x18393919c 0x1839395cc 0x183869280 0x18e9e00cc 0x189056df8 0x10013655c 0x198b468b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Thank you for the help.

**Comment by kitasuke** [comment] 2015-07-28 05:02
Hi,
It may be same case with #48 ?
Presenting only one custom view controller hasn't supported yet, but it will be fixed soon.

**Comment by ds1239** [comment] 2015-07-28 12:30
I added an additional view controller to test that out, and that was the problem. However, now I am experiencing another one. The selected tab moves to the side of the screen, not to the center. Also, the web views in the custom controllers are not loading anything now.

**Comment by ds1239** [comment] 2015-07-28 12:38
Also, when I try to create the views with a for loop, I get the following errors:
2015-07-28 08:35:32.350 YidKit[698:152486] _BSMachError: (os/kern) invalid capability (20)
2015-07-28 08:35:32.351 YidKit[698:152486] _BSMachError: (os/kern) invalid name (15)

Here is the code 

        for(var i = 0; i < daveningURLs.count; i++)
        {
            let viewController = self.storyboard?.instantiateViewControllerWithIdentifier("DataViewController") as! DataViewController
            viewController.title = daveningTitles[i]
            viewController.currentUrl = daveningURLs[i]
            viewControllers.append(viewController)
        }

**Comment by kitasuke** [comment] 2015-07-29 02:46
Could you give me all the options you set for `PagingMenuOptions`? Because it's much easier to find out the reason of the unexpected behaviour. Also it would be great if I could see its screenshots.

**Comment by ds1239** [comment] 2015-07-29 04:03
Here is my code for the options: let options = PagingMenuOptions()
        options.menuHeight = 44
        options.menuDisplayMode = PagingMenuOptions.MenuDisplayMode.FlexibleItemWidth(centerItem: true, scrollingMode: PagingMenuOptions.MenuScrollingMode.ScrollEnabledAndBouces)
        options.textColor = UIColor.blackColor()
        options.backgroundColor = UIColor(netHex: 0xFCFCFC)
        options.menuItemMode = PagingMenuOptions.MenuItemMode.Underline(height: 2, color: UIColor(netHex:0x0066FF))
        
        let pagingMenuController = self.childViewControllers.first as! PagingMenuController
        pagingMenuController.delegate = self
        pagingMenuController.setup(viewControllers: viewControllers, options: options)

Also, I just realized that the selected tab centers (as it should) while running in the iOS simulator, but it doesn't center when on a physical device (see image below). 
![img_4979](https://cloud.githubusercontent.com/assets/11168127/8949742/3c3976fe-3585-11e5-8374-fb32cfe4e106.PNG)

**Comment by kitasuke** [comment] 2015-07-29 04:26
Thanks for helpful info. Also could you tell me what version of `PagingMenuController` you are using?

**Comment by ds1239** [comment] 2015-07-29 04:29
I am using the version for swift 2.

**Comment by kitasuke** [comment] 2015-07-29 04:38
I'm digging into more detail with your options and try to tell you what's wrong ASAP. Please wait a bit more.

FYI, since Xcode 7 is still beta, any project written in Swift 2.0 can not be submitted at this moment if I'm correct.

**Comment by ds1239** [comment] 2015-07-29 16:13
Thank you, I apreciate all of the help.

**Comment by kitasuke** [comment] 2015-08-02 07:10
> The selected tab moves to the side of the screen, not to the center. Also, How do I make the menu's appearance not opaque?

I set same options as yours and it works fine on my device. I'll look into more detail and let you know if there is something wrong.
I didn't make it opaque. How do you think it's opaque?

**Comment by kitasuke** [comment] 2015-10-01 11:21
Please try the latest version and reopen this issue if there is still something wrong.

**Closed by kitasuke** 2015-10-01 11:21 UTC
