### ISSUE TITLE
Access pagingMenuController frame from child view

### ISSUE THREAD

**Issue by chashmeetsingh** [kitasuke/PagingMenuController#254] opened 2016-07-06 01:08 UTC
- Expected behavior and actual behavior.
- Steps to reproduce the problem.
- Specifications like the version of the project, library, or Swift.
  Downloaded the project as zip tried running example won't work

**Comment by chashmeetsingh** [comment] 2016-07-06 01:10
@kitasuke

**Comment by kitasuke** [comment] 2016-07-06 01:19
- Did you `pod install` in terminal?
- Is it beta Xcode?

Can you share what the error message on Xcode?

**Comment by chashmeetsingh** [comment] 2016-07-06 01:28
i fixed it by using the pod and adding target and removing rest of the stuff
I need help adding the Underline option Inside a view controller as a view

**Comment by kitasuke** [comment] 2016-07-06 01:31
I'm not quite sure your situation. Could you share what's your expected behaviour in more detail and your source code here?

**Comment by chashmeetsingh** [comment] 2016-07-06 01:35
```
private struct PagingMenuOptions: PagingMenuControllerCustomizable {
    private var componentType: ComponentType {
        return .All(menuOptions: MenuOptions(), pagingControllers: pagingControllers)
    }

    private var pagingControllers: [UIViewController] {
        let viewController1 = LatestEpisodeViewController()
        let viewController2 = ShowInfoViewController()
        return [viewController1, viewController2]
    }

    private struct MenuOptions: MenuViewCustomizable {
        var displayMode: MenuDisplayMode {
            return .SegmentedControl
        }
        var itemsOptions: [MenuItemViewCustomizable] {
            return [MenuItem1(), MenuItem2()]
        }
    }

    private struct MenuItem1: MenuItemViewCustomizable {
        var displayMode: MenuItemDisplayMode {
            return .Text(title: MenuItemText(text: "First Menu"))
        }
    }
    private struct MenuItem2: MenuItemViewCustomizable {
        var displayMode: MenuItemDisplayMode {
            return .Text(title: MenuItemText(text: "Second Menu"))
        }
    }
}
```
in viewDidLoad()
```
func prepareTabBar() {

        let options = PagingMenuOptions()
        let pagingMenuController = PagingMenuController(options: options)
        pagingMenuController.view.frame.origin.y += 64
        pagingMenuController.view.frame.size.height -= 64

        view.addSubview(pagingMenuController.view)
    }
```
I am not able to change tabs

**Comment by kitasuke** [comment] 2016-07-06 01:41
I still don't know what you really want to do with this library...
What does `change tags` mean?
- change dynamically?
- change what?

**Comment by kitasuke** [comment] 2016-07-06 01:42
Is `change tabs` related to `adding the Underline option Inside a view controller as a view`?

**Comment by chashmeetsingh** [comment] 2016-07-06 01:43
I have a view controller with only an image view, I want to add the tab bar below that image view

**Comment by chashmeetsingh** [comment] 2016-07-06 01:44
Also there is no method/functionality to pass in data to the view controllers declared in the strust

**Comment by kitasuke** [comment] 2016-07-06 01:48
Try below

```
func prepareTabBar() {
        let options = PagingMenuOptions()
        let pagingMenuController = PagingMenuController(options: options)
        pagingMenuController.view.frame.origin.y += 64
        pagingMenuController.view.frame.size.height -= 64

        addChildViewController(pagingMenuController)
        view.addSubview(pagingMenuController.view)
        pagingMenuController.didMoveToParentViewController(self)
}
```

**Comment by chashmeetsingh** [comment] 2016-07-06 01:51
awesome worked! How do I pass data from the parent view controller into one of the view controllers in the struct?

**Comment by kitasuke** [comment] 2016-07-06 01:52
What kind of data do you want to pass?

**Comment by chashmeetsingh** [comment] 2016-07-06 01:54
for example any int ?

**Comment by kitasuke** [comment] 2016-07-06 01:58
Why don't you create a variable or method in your child view controller? You can pass any data to child view controller when you get delegate method(`func willMoveToPageMenuController(menuController: UIViewController, previousMenuController: UIViewController)`) call for instance.

**Comment by chashmeetsingh** [comment] 2016-07-06 02:00
any example for this?

**Comment by kitasuke** [comment] 2016-07-06 02:06
Not sure if it's useful, but like this?

```
class PagingMenuViewController: UIViewController {
    var options: PagingMenuControllerCustomizable!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        let pagingMenuController = self.childViewControllers.first as! PagingMenuController
        pagingMenuController.delegate = self
        pagingMenuController.setup(options)
    }
}

extension PagingMenuViewController: PagingMenuControllerDelegate {
    // MARK: - PagingMenuControllerDelegate

    func willMoveToPageMenuController(menuController: UIViewController, previousMenuController: UIViewController) {
        guard let customViewController = menuController as? CustomViewController else { return }
        customViewController.id = 3
    }

    func didMoveToPageMenuController(menuController: UIViewController, previousMenuController: UIViewController) {
    }
    
    func willMoveToMenuItemView(menuItemView: MenuItemView, previousMenuItemView: MenuItemView) {
    }
    
    func didMoveToMenuItemView(menuItemView: MenuItemView, previousMenuItemView: MenuItemView) {
    }
}
```

**Comment by kitasuke** [comment] 2016-07-06 02:06
there should be `id` variable in CustomViewController

**Comment by chashmeetsingh** [comment] 2016-07-06 02:08
hmm and what about dynamically adding view controllers?

**Comment by kitasuke** [comment] 2016-07-06 02:17
It's not perfectly supported, but recreate a new option with the new view controllers.

```
let oldOptions = PagingMenuOptions(pagingControllers: [UIViewController()])

let newOptions = PagingMenuOptions(pagingControllers: [UIViewController(), UIViewController()])
pagingMenuController.setup(newOptions)

private struct PagingMenuOptions: PagingMenuControllerCustomizable {
    private var componentType: ComponentType {
        return .All(menuOptions: MenuOptions(), pagingControllers: pagingControllers)
    }

    private var pagingControllers: [UIViewController] = []
    
    init(pagingControllers: [UIViewController]) {
        self.pagingControllers = pagingControllers
    }
}
```

**Comment by chashmeetsingh** [comment] 2016-07-06 02:19
and how to change the colour of tabs? the backgroundColor property as the name suggests should have changed the tab bar items colour not the view controllers?

**Comment by kitasuke** [comment] 2016-07-06 02:20
here is options for tab
```
public protocol MenuViewCustomizable {
    var backgroundColor: UIColor { get }
    var selectedBackgroundColor: UIColor { get }
    var height: CGFloat { get }
    var animationDuration: NSTimeInterval { get }
    var deceleratingRate: CGFloat { get }
    var selectedItemCenter: Bool { get }
    var displayMode: MenuDisplayMode { get }
    var focusMode: MenuFocusMode { get }
    var dummyItemViewsSet: Int { get }
    var menuPosition: MenuPosition { get }
    var dividerImage: UIImage? { get }
    var itemsOptions: [MenuItemViewCustomizable] { get }
}
```

**Comment by chashmeetsingh** [comment] 2016-07-06 02:25
```
private struct PagingMenuOptions: PagingMenuControllerCustomizable {
   private var backgroundColor: UIColor {
        return MaterialColor.grey.darken4
    }

    private var componentType: ComponentType {
        return .All(menuOptions: MenuOptions(), pagingControllers: pagingControllers)
    }

    init(pagingControllers: [UIViewController]) {
        self.pagingControllers = pagingControllers
    }

    private var pagingControllers: [UIViewController] = []

    private struct MenuOptions: MenuViewCustomizable {
        var displayMode: MenuDisplayMode {
            return .SegmentedControl
        }
        var itemsOptions: [MenuItemViewCustomizable] {
            return [MenuItem1(), MenuItem2(), MenuItem3()]
        }
    }

    private struct MenuItem1: MenuItemViewCustomizable {
        var displayMode: MenuItemDisplayMode {
            return .Text(title: MenuItemText(text: "INFO"))
        }
    }
    private struct MenuItem2: MenuItemViewCustomizable {
        var displayMode: MenuItemDisplayMode {
            return .Text(title: MenuItemText(text: "Latest Episode"))
        }
    }
    private struct MenuItem3: MenuItemViewCustomizable {
        var displayMode: MenuItemDisplayMode {
            return .Text(title: MenuItemText(text: "Seasons"))
        }
    }
}
```
```
func prepareTabBar() {
        let oldOptions = PagingMenuOptions(pagingControllers: [UIViewController()])

        let newOptions = PagingMenuOptions(pagingControllers: [ShowInfoViewController(), LatestEpisodeViewController(), SeasonsViewController(show: show)])

        let pagingMenuController = PagingMenuController(options: oldOptions)
        pagingMenuController.setup(newOptions)
        pagingMenuController.view.frame.origin.x = 0
        pagingMenuController.view.frame.origin.y = self.view.frame.height * 1 / 3

        addChildViewController(pagingMenuController)
        view.addSubview(pagingMenuController.view)
        pagingMenuController.didMoveToParentViewController(self)
    }
```
is this that has to be done? as I get an error `'number of menu items and view controllers doesn't match'`

**Comment by chashmeetsingh** [comment] 2016-07-06 02:30
worked! but still not able to change tab colour
```
private var selectedBackgroundColor: UIColor {
        return MaterialColor.grey.darken4
    }
```

**Comment by kitasuke** [comment] 2016-07-06 02:32
try this

```
    private struct MenuOptions: MenuViewCustomizable {
        var selectedBackgroundColor: UIColor {
            return MaterialColor.grey.darken4
        }
        var displayMode: MenuDisplayMode {
            return .SegmentedControl
        }
        var itemsOptions: [MenuItemViewCustomizable] {
            return [MenuItem1(), MenuItem2(), MenuItem3()]
        }
    }
```

**Comment by chashmeetsingh** [comment] 2016-07-06 02:37
nice!

**Comment by chashmeetsingh** [comment] 2016-07-06 05:42
@kitasuke not able to change frame from tab view controllers for pagingMenuController

**Comment by kitasuke** [comment] 2017-02-04 07:09
Changing frame might not be an issue because of this library, so I close this issue.

**Closed by kitasuke** 2017-02-04 07:09 UTC
